### We divide our dataset into some folds and run some turns

### In each turn we test model on 1 fold and train on others

### This process continues for all no. of folds

### Then avg score based on scores of all turns is calculated

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [17]:
digits = load_digits()

In [18]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size = 0.3)

In [19]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9481481481481482

In [20]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.987037037037037

In [21]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9722222222222222

The disadvantage above is as train and test datasets will change score of models will also change which is not suitable

### Using KFold Now

In [22]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)   #no of folds

kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [23]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [24]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [26]:
# Stratified K -Fold ---> it will divide each fold into categories in uniform way(folds will bw mixed not completely unique)

from sklearn.model_selection import StratifiedKFold

folds = StratifiedKFold(n_splits=3)

In [27]:
scores_l = []
scores_sv = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index], \
                                     digits.target[train_index],digits.target[test_index]
                                     
scores_l.append(get_score(LogisticRegression(max_iter=1500),X_train,X_test,y_train,y_test))
scores_sv.append(get_score(SVC(),X_train,X_test,y_train,y_test))
scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))
                                                    


In [28]:
scores_l

[0.9165275459098498]

In [29]:
scores_sv

[0.9549248747913188]

In [30]:
scores_rf

[0.9181969949916527]

Checking same above thing with cross val score

In [31]:
from sklearn.model_selection import cross_val_score

cross_val_score(LogisticRegression(),digits.data,digits.target)



C:\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [32]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [33]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.925     , 0.91666667, 0.96100279, 0.95264624, 0.93314763])

In [34]:
cross_val_score(RandomForestClassifier(n_estimators=200),digits.data,digits.target)

array([0.93055556, 0.91666667, 0.95821727, 0.96100279, 0.92479109])

In [35]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)

array([0.94166667, 0.88888889, 0.95543175, 0.97214485, 0.92479109])